"""Stable Phase-1 data contracts. No BRAIN network operations live here."""

from __future__ import annotations

from enum import Enum


class CheckPhase(str, Enum):
    PRE_TAG = "PRE_TAG"
    RECHECK = "RECHECK"
    FINAL = "FINAL"


class CandidateLifecycle(str, Enum):
    DISCOVERED = "DISCOVERED"
    PLANNED = "PLANNED"
    SIMULATION_PENDING = "SIMULATION_PENDING"
    SIMULATION_RUNNING = "SIMULATION_RUNNING"
    SIMULATION_COMPLETE = "SIMULATION_COMPLETE"
    SIGNAL_ANALYZED = "SIGNAL_ANALYZED"
    PRE_CHECK_REPAIR = "PRE_CHECK_REPAIR"
    LOCAL_PRE_GATE_PASS = "LOCAL_PRE_GATE_PASS"
    PRE_TAG_CHECK_PENDING = "PRE_TAG_CHECK_PENDING"
    PRE_TAG_CHECK_COMPLETE = "PRE_TAG_CHECK_COMPLETE"
    CHECK_REPAIR = "CHECK_REPAIR"
    PRE_TAG_CHECK_PASS = "PRE_TAG_CHECK_PASS"
    FAMILY_DEDUP = "FAMILY_DEDUP"
    PRE_TAG_FINALIST = "PRE_TAG_FINALIST"
    DESCRIPTION_DRAFT = "DESCRIPTION_DRAFT"
    DESCRIPTION_VALIDATED = "DESCRIPTION_VALIDATED"
    AWAITING_MANUAL_PROPERTIES = "AWAITING_MANUAL_PROPERTIES"
    PPL_TAGGED = "PPL_TAGGED"
    FINAL_CHECK_PENDING = "FINAL_CHECK_PENDING"
    FINAL_CHECK_COMPLETE = "FINAL_CHECK_COMPLETE"
    FINAL_CHECK_PASS = "FINAL_CHECK_PASS"
    READY_FOR_MANUAL_SUBMIT = "READY_FOR_MANUAL_SUBMIT"
    SUBMITTED = "SUBMITTED"
    NEAR_PASS = "NEAR_PASS"
    NEEDS_MANUAL_DESCRIPTION = "NEEDS_MANUAL_DESCRIPTION"
    OPERATOR_VALIDATION = "OPERATOR_VALIDATION"
    CORRELATION_DIAGNOSIS = "CORRELATION_DIAGNOSIS"
    STRUCTURAL_FAIL = "STRUCTURAL_FAIL"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class SimulationStatus(str, Enum):
    NONE = "NONE"
    SUBMITTED = "SUBMITTED"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    ERROR = "ERROR"
    AUTH_ERROR = "AUTH_ERROR"
    INVALID = "INVALID"
    UNCERTAIN_SUBMISSION = "UNCERTAIN_SUBMISSION"
    UNKNOWN = "UNKNOWN"


class ExecutionAction(str, Enum):
    CACHE_RESTORE = "CACHE_RESTORE"
    RESUME_EXISTING = "RESUME_EXISTING"
    NEW_SIMULATION_REQUIRED = "NEW_SIMULATION_REQUIRED"
    STOP_INVALID = "STOP_INVALID"
    HOLD_UNCERTAIN = "HOLD_UNCERTAIN"
    RETRY_PER_V21_POLICY = "RETRY_PER_V21_POLICY"
    NEEDS_LIVE_RECONCILE = "NEEDS_LIVE_RECONCILE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NONE = "NONE"


class SimulationFreshness(str, Enum):
    CONFIRMED_COMPLETE = "CONFIRMED_COMPLETE"
    STALE_NONTERMINAL = "STALE_NONTERMINAL"
    LOCAL_ERROR = "LOCAL_ERROR"
    UNKNOWN = "UNKNOWN"


class RunStatus(str, Enum):
    CREATED = "CREATED"
    PLANNED = "PLANNED"
    RECONCILED = "RECONCILED"
    READY_FOR_EXECUTION = "READY_FOR_EXECUTION"
    EXECUTING = "EXECUTING"
    PAUSED = "PAUSED"
    AWAITING_MANUAL_ACTION = "AWAITING_MANUAL_ACTION"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


LOCAL_PRE_GATE_FIELDS = (
    "theme_settings_match",
    "dataset_allowed",
    "simulation_sharpe",
    "simulation_turnover",
    "local_data_field_count",
    "legacy_unique_operator_count",
    "pp_total_operator_count_estimate",
    "theme_turnover_precondition",
    "candidate_structure_valid",
)

LIVE_BASE_GATE_CHECKS = (
    "SHARPE",
    "TURNOVER",
    "OPERATOR_COUNT",
    "DATA_FIELD_COUNT",
    "SUB_UNIVERSE",
    "POWER_POOL_CORRELATION",
)

LIVE_THEME_GATE_CHECKS = (
    "HIGH_TURNOVER",
    "HIGH_TURNOVER_RETURNS_RATIO",
    "CLASSIFICATION_HIGH_TURNOVER",
    "THEME_MATCH",
)

RECONCILE_PRECEDENCE = {
    "complete_simulation": ["ALPHA_RESULTS_DB_COMPLETE"],
    "nonterminal_simulation": ["LIVE_BRAIN_SIMULATION", "ALPHA_RESULTS_DB"],
    "check": ["LIVE_CHECK", "CACHED_CHECK", "PRESET"],
    "properties": [
        "LIVE_ALPHA_DETAILS",
        "PPL_RUNNER_DB",
        "PPL_STATE_JSON",
        "MANUAL_EVIDENCE",
    ],
    "workflow": ["PPL_RUNNER_DB", "PPL_STATE_JSON"],
}

OPERATOR_CAPABILITY_STATUSES = (
    "VERIFIED_API",
    "VERIFIED_PROJECT",
    "VALIDATED_SINGLE",
    "UNVERIFIED",
    "NEEDS_REVALIDATION",
    "INVALID_SYNTAX",
    "UNAVAILABLE",
)

ERROR_NATURES = ("DETERMINISTIC", "TRANSIENT", "UNKNOWN")

REPAIR_PLAN_STATUSES = (
    "PLANNED", "BLOCKED_OPERATOR_VALIDATION", "BLOCKED_BUDGET", "BLOCKED_CYCLE",
    "BLOCKED_DEPTH", "BLOCKED_STRUCTURE", "READY", "DISPATCHED", "EXECUTED",
    "EVALUATED_ACCEPT", "EVALUATED_REJECT", "STOPPED",
    # Durable deferred statuses produced during Production initial search.
    "DEFERRED_INITIAL_SEARCH", "DEFERRED_PHASE_END",
)
